stages:
  - build
  - deploy

before_script:
    - docker info
    - javac -version

variables:
    IMAGE_OPENJDK_GRADLE: gradle:7.3.3-jdk17-alpine
    IMAGE_DOCKER_DIND: docker:20.10.16

build:
    image: $IMAGE_OPENJDK_GRADLE
    stage: build
    script:
        - echo "Compiling the code..."
        - cd $CI_PROJECT_DIR/frontend
        - sh gradlew clean assemble
        - cd .. 
        - cd $CI_PROJECT_DIR/kerjasama
        - sh gradlew clean assemble
        - cd ..
        - cd $CI_PROJECT_DIR/program
        - sh gradlew clean assemble
        - cd ..
        - cd $CI_PROJECT_DIR/user
        - sh gradlew clean assemble
        - cd ..
    artifacts:
        paths:
            - frontend/build/libs/frontend-0.0.1-SNAPSHOT.jar
            - kerjasama/build/libs/kerjasama-0.0.1-SNAPSHOT.jar
            - program/build/libs/program-0.0.1-SNAPSHOT.jar
            - user/build/libs/user-0.0.1-SNAPSHOT.jar

deploy-railway:
  stage: deploy
  image: $IMAGE_DOCKER_DIND
  only:
    - pushes
    - main
  script:
    - apt-get update && apt-get install -y curl
    - curl -fsSL https://railway.app/install.sh | sh
    - railway up --service=$RAILWAY_SERVICE_NAME -d
